openapi: 3.1.0
info:
  title: Finzly Connect API (Split Specs Aggregator)
  description: Aggregated entrypoint that references payment and customer API specs.
  version: 0.1.0
  contact:
    name: Finzly Developer Support
    url: https://api.finzly.io/
servers:
  - url: https://api.finzly.io
    description: Finzly production (placeholder)
  - url: https://sandbox.api.finzly.io
    description: Finzly sandbox (placeholder)
security:
  - bearerAuth: []
tags:
  - name: Payment APIs
    description: Sample endpoints for initiating and tracking payment requests.
  - name: Customer APIs
    description: Sample endpoints for onboarding and retrieving customer profiles.

paths:
  /payments:
    $ref: ./payment-api/openapi.yaml#/paths/~1payments
  /payments/{paymentId}:
    $ref: ./payment-api/openapi.yaml#/paths/~1payments~1{paymentId}
  /customers:
    $ref: ./customer-api/openapi.yaml#/paths/~1customers
  /customers/{customerId}:
    $ref: ./customer-api/openapi.yaml#/paths/~1customers~1{customerId}

components:
  schemas:
    CreatePaymentRequest:
      $ref: ./payment-api/openapi.yaml#/components/schemas/CreatePaymentRequest
    Payment:
      $ref: ./payment-api/openapi.yaml#/components/schemas/Payment
    CreateCustomerRequest:
      $ref: ./customer-api/openapi.yaml#/components/schemas/CreateCustomerRequest
    Customer:
      $ref: ./customer-api/openapi.yaml#/components/schemas/Customer
    Problem:
      $ref: ./payment-api/openapi.yaml#/components/schemas/Problem
  securitySchemes:
    bearerAuth:
      $ref: ./payment-api/openapi.yaml#/components/securitySchemes/bearerAuth
