openapi: 3.1.0
info:
  title: Finzly Connect API (Sample)
  description: |
    Temporary sample API specification for the Finzly API Developer Portal.
    Replace these placeholder endpoints with production Finzly API contracts.
  version: 0.1.0
  contact:
    name: Finzly Developer Support
    url: https://api.finzly.io/
servers:
  - url: https://api.finzly.io
    description: Finzly production (placeholder)
  - url: https://sandbox.api.finzly.io
    description: Finzly sandbox (placeholder)
security:
  - bearerAuth: []
tags:
  - name: Payment APIs
    description: Sample endpoints for initiating and tracking payment requests.
  - name: Customer APIs
    description: Sample endpoints for onboarding and retrieving customer profiles.
paths:
  /payments:
    post:
      summary: Create a payment
      operationId: createPayment
      tags:
        - Payment APIs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentRequest'
      responses:
        '201':
          description: Payment created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
        '400':
          description: Validation error.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '401':
          description: Unauthorized.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

  /payments/{paymentId}:
    get:
      summary: Get payment by ID
      operationId: getPayment
      tags:
        - Payment APIs
      parameters:
        - name: paymentId
          in: path
          required: true
          description: Unique payment identifier.
          schema:
            type: string
      responses:
        '200':
          description: Payment details returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
        '404':
          description: Payment not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

  /customers:
    post:
      summary: Create customer
      operationId: createCustomer
      tags:
        - Customer APIs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequest'
      responses:
        '201':
          description: Customer created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Validation error.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

  /customers/{customerId}:
    get:
      summary: Get customer by ID
      operationId: getCustomer
      tags:
        - Customer APIs
      parameters:
        - name: customerId
          in: path
          required: true
          description: Unique customer identifier.
          schema:
            type: string
      responses:
        '200':
          description: Customer details returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Customer not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

components:
  schemas:
    CreatePaymentRequest:
      type: object
      required:
        - amount
        - currency
        - rail
        - beneficiaryId
      properties:
        amount:
          type: number
          format: double
          example: 1250.75
        currency:
          type: string
          example: USD
        rail:
          type: string
          enum: [ACH, FEDWIRE, RTP, FEDNOW]
          example: ACH
        beneficiaryId:
          type: string
          example: ben_001
        remittanceInformation:
          type: string
          example: Invoice 2026-0021

    Payment:
      type: object
      properties:
        id:
          type: string
          example: pay_8f29d3
        status:
          type: string
          enum: [PENDING, PROCESSING, COMPLETED, FAILED]
          example: PENDING
        amount:
          type: number
          format: double
          example: 1250.75
        currency:
          type: string
          example: USD
        rail:
          type: string
          example: ACH
        createdAt:
          type: string
          format: date-time
          example: '2026-02-26T13:25:10Z'

    CreateCustomerRequest:
      type: object
      required:
        - type
        - legalName
      properties:
        type:
          type: string
          enum: [BUSINESS, INDIVIDUAL]
          example: BUSINESS
        legalName:
          type: string
          example: Acme Manufacturing LLC
        email:
          type: string
          format: email
          example: treasury@acme.example
        country:
          type: string
          example: US

    Customer:
      type: object
      properties:
        id:
          type: string
          example: cus_49ca21
        type:
          type: string
          example: BUSINESS
        legalName:
          type: string
          example: Acme Manufacturing LLC
        status:
          type: string
          enum: [PENDING_REVIEW, ACTIVE, SUSPENDED]
          example: ACTIVE
        createdAt:
          type: string
          format: date-time
          example: '2026-02-26T13:29:11Z'

    Problem:
      type: object
      properties:
        type:
          type: string
          format: uri
          example: https://api.finzly.io/problems/invalid-request
        title:
          type: string
          example: Invalid request
        status:
          type: integer
          example: 400
        detail:
          type: string
          example: One or more request fields are invalid.
        instance:
          type: string
          format: uri
          example: /problems/invalid-request/abcd1234

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer token issued for Finzly Connect API access.
